set -g default-terminal "screen-256color"
set-option -sa terminal-overrides ",xterm*:Tc"
set-option -g status-position bottom

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind r
bind r source-file ~/.tmux.conf

bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

bind -r m resize-pane -Z

set -g base-index 1

bind e if-shell 'tmux has-session -t oussama' 'kill-session; switch-client -t oussama' 'detach'

set -g mouse off

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode after dragging with mouse

bind-key -r f run-shell "tmux neww ~/.tmux-sessionizer"

bind -r o popup -E -d "#{pane_current_path}" -w 90% -h 90% "bash -c '/home/oussama/.opencode/bin/opencode; exit'"

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator' # for navigating panes and vim/nvim with Ctrl-hjkl
set -g @plugin 'tmux-plugins/tmux-sensible' # set sensible defaults for tmux
set -g @plugin 'tmux-plugins/tmux-yank'

set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'main'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
