gui:
  theme:
    activeBorderColor:
      - "#AEC6CF"
    inactiveBorderColor:
      - "#A0A0A0"
    optionsTextColor:
      - "#FFFFFF"
    textColor:
      - "#CDCDCD"
    selectedLineBgColor:
      - "#506075"
    selectedRangeBgColor:
      - "#607085"
    commitAuthorColor:
      - "#BB9DBD"
    commitShaColor:
      - "#AEAED1"
    commitTitleColor:
      - "#FFFFFF"
    unstagedChangesColor:
      - "#F3BE7C"
