general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # turn on display after sleep
}

# Dim the screen after 4 minutes
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 10         # save current brightness and set to 10%
    on-resume = brightnessctl -r                 # restore brightness
}

# Lock the screen after 5 minutes
listener {
    timeout = 300
    on-timeout = loginctl lock-session           # trigger lock session
}

# Turn off display after 6 minutes
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off       # turn off screen
    on-resume = hyprctl dispatch dpms on         # turn on screen
}

# Suspend system after 20 minutes
listener {
    timeout = 1200
    on-timeout = systemctl suspend               # suspend pc
}
