[colors]
background = #161B22
foreground = #FFFFFF
primary = #0366d6
disabled = #c5dae5
alert = #937ead

; [global/wm]
; margin-top = 20
; margin-bottom = 20

[wm]
name = i3

##########################
### Single Combined Bar
##########################

[bar/main]
monitor = ${env:MONITOR:}
top = true
fixed-center = false
width = 100%
height = 35
wm-restack = ${wm.name}
override-redirect = false  # Set to false to let the window manager handle it

# Offsets
# offset-x = 2%
# offset-y = 10

# Colors
background = ${colors.background}
foreground = ${colors.foreground}

# Font
font-0 = JetBrainsMono Nerd Font:size=12;2
font-1 = JetBrainsMono Nerd Font:size=14;4
line-size = 3
line-color = ${colors.primary}

# Borders
; border-size = 2
; border-color = ${colors.background}
; radius = 10.0

# Padding
padding-left = 20px
padding-right = 20px

# Modules
module-margin-left = 15px
module-margin-right = 15px

# fixed-center = true


modules-left = date player songname
modules-center = xworkspaces 
modules-right = cpu memory temperature pulseaudio powermenu


# Left Modules
# modules-left = date xworkspaces 

# Center Modules
# modules-center =  songname

# Right Modules
# modules-right = cpu memory temperature pulseaudio powermenu

############################################################################
## ALL MODULES ##############################################################
##############################################################################
[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-foreground = ${colors.primary}
label-active-padding = 5px
label-active-underline = ${colors.primary}
label-active-background = ${colors.background}

label-occupied = %name%
label-occupied-padding = 5px

label-urgent = %name%
label-urgent-background = ${colors.background}
label-urgent-padding = 5px

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 5px

[module/cpu]
type = internal/cpu
interval = 2
warn-percentage = 95

format = <ramp-load> <label>
label = %percentage%%
label-warning = %percentage%%

ramp-load-0 =  
ramp-load-1 =  
ramp-load-2 =  
ramp-load-3 =  
ramp-load-4 =  
ramp-load-5 =  
ramp-load-6 =  
ramp-load-7 =  

ramp-load-foreground = ${colors.primary}

[module/memory]
type = internal/memory
interval = 1
warn-percentage = 95

format = <ramp-used> <label>
label = %mb_used%
label-warn = %mb_used%

ramp-used-0 =  
ramp-used-1 =  
ramp-used-2 =  
ramp-used-3 =  
ramp-used-4 =  
ramp-used-5 =  
ramp-used-6 =  
ramp-used-7 =  

ramp-used-foreground = ${colors.primary}

[module/date]
type = internal/date
interval = 1.0
time = " %I:%M %p"
time-alt = " %a, %d %b %Y"

format = <label>
label = %time%

[module/pulseaudio]
type = internal/pulseaudio

format-volume = <ramp-volume>  <label-volume>
label-volume = %percentage%%
label-muted =  Muted
label-muted-foreground = ${colors.disabled}

ramp-volume-0 = 
ramp-volume-1 = 
ramp-volume-2 = 
ramp-volume-foreground = ${colors.primary}
click-right = pavucontrol

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 60
units = false
format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = TEMP %temperature-c%
label-warn = TEMP %temperature-c%
label-warn-foreground = ${colors.alert}
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.primary}

[module/powermenu]
type = custom/text
format = <label>
label = 󰐥
label-font = 1
label-background = ${colors.background}
label-foreground = ${colors.primary}
click-left = ~/.config/rofi/powermenu/powermenu.sh

[module/player]
type = custom/script
exec = ~/.config/polybar/mytheme/scripts/player.sh
interval = 0.5

[module/songname]
type = custom/script
exec = ~/.config/polybar/mytheme/scripts/songname.sh
click-left = ~/.config/rofi/applets/bin/mpd.sh
interval = 3

[settings]
screen-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = true
