[[mgr.prepend_keymap]]
on   = [ "g", "/" ]
run  = "cd /"
desc = "Cd to root"

[[mgr.prepend_keymap]]
on   = [ "g", "z" ]
run  = "cd ~/data/"
desc = "access Data disk"

[[mgr.prepend_keymap]]
on   = [ "g", "e" ]
run  = "cd ~/Documents/"
desc = "access Docs"
