[mgr]
cwd = { fg = "#c1c1c1" }
hovered = { bg = "#222222" }
find_keyword = { fg = "#e78a53", bold = true }
marker_copied = { bg = "#fbcb97" }
marker_cut = { bg = "#e78a53" }
tab_active = { fg = "#c1c1c1", bold = true }
tab_inactive = { fg = "#999999" }
border_style = { fg = "#333333" }

[mode]
normal_main = { fg = "#c1c1c1", bg = "#000000" }
select_main = { fg = "#c1c1c1", bg = "#222222" }

[status]
overall = { fg = "#c1c1c1", bg = "#000000" }
perm_type = { fg = "#888888" }
perm_read = { fg = "#fbcb97" }
perm_write = { fg = "#e78a53" }
perm_exec = { fg = "#5f8787" }
progress_normal = { fg = "#c1c1c1", bg = "#121212" }
progress_error = { fg = "#5f8787" }

[pick]
border = { fg = "#333333" }
active = { fg = "#c1c1c1", bg = "#222222" }
inactive = { fg = "#c1c1c1" }

[input]
border = { fg = "#333333" }
value = { fg = "#c1c1c1" }
selected = { bg = "#222222" }

[cmp]
border = { fg = "#333333" }
active = { fg = "#c1c1c1", bg = "#222222" }
inactive = { fg = "#c1c1c1" }

[tasks]
border = { fg = "#333333" }
hovered = { bg = "#222222" }

[help]
on = { fg = "#888888" }
desc = { fg = "#c1c1c1" }
hovered = { bg = "#222222" }

[notify]
title_info = { fg = "#888888" }
title_warn = { fg = "#e78a53" }
title_error = { fg = "#5f8787" }

[filetype]
rules = [
        { name = "*/", fg = "#888888" },
        { name = "*", fg = "#c1c1c1" }
]

[icon]
prepend_conds = [
    { if = "dir", text = "", fg = "#888888" },
    { if = "link", text = "", fg = "#999999" },
    { if = "exec", text = "", fg = "#5f8787" }
]

[icon]
prepend_conds = [
    { if = "dir", text = "", fg = "#9bb4bc" }, #type color, directory icon
    { if = "link", text = "", fg = "#aeaed1" }, #constant color, link icon
    { if = "exec", text = "", fg = "#c48282" } #func color, executable icon.
]
