[manager]
show_hidden = true
linemode = "size"

[open]
rules = [
    { mime = "image/*", use = "view_image" },
    { mime = "text/*", use = "edit" },
    { mime = "inode/directory", use = "change_dir" },  # Directory rule
    { name = "*", use = "edit" }  # Fallback rule
]

[opener]
edit = [
    { run = 'nvim "$@"', block = true, for = "unix" },
]
view_image = [
    { run = 'feh "$@"', orphan = true, for = "unix" }
]
change_dir = [
    { run = 'cd "$@" && exec bash', block = true, for = "unix" }
]
